ingress:
  enabled: true
  path: /
  hosts:
    - s3.k8svkr.eterfund.ru
  # tls:
    # - secretName: minio-tls
      # hosts:
        # - s3.k8s.eterfund.ru
  annotations:
    kubernetes.io/ingress.class: traefik

consoleIngress:
  enabled: true
  path: /
  hosts:
    - minio.k8svkr.eterfund.ru
  # tls:
    # - secretName: minio-console-tls
      # hosts:
        # - minio.k8s_vkr.eterfund.ru
  annotations:
    kubernetes.io/ingress.class: traefik

rootUser: admin
replicas: 1
mode: standalone
environment:
  MINIO_SERVER_URL: "https://s3.k8svkr.eterfund.ru:443"

tls:
  enabled: false
  certSecret: ''
  publicCrt: public.crt
  privateKey: private.key

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 512Mi
  storageClass: openebs-hostpath

service:
  type: ClusterIP
  clusterIP: ~
  port: '9000'

consoleService:
  type: ClusterIP
  clusterIP: ~
  port: '9001'

resources:
  requests:
    memory: 2Gi

policies:
  - name: backup
    statements:
      - resources:
          - 'arn:aws:s3:::backup'
        actions:
          - "s3:*"
# 