---
controller:
  resources:
    limits:
      memory: 512Mi
      cpu: 200m
    requests:
      cpu: 100m
      memory: 512Mi
  metrics:
    enabled: true
    applicationLabels:
      enabled: false
      labels: []
    service:
      annotations: {}
      labels: {}
      servicePort: 8082
      portName: http-metrics
    serviceMonitor:
      enabled: false
      interval: 30s
      relabelings: []
      metricRelabelings: []
      selector: {}
      scheme: ""
      tlsConfig: {}
      additionalLabels: {}
    rules:
      enabled: false
      spec: []
dex:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

redis:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

global:
  domain: argocd.k8svkr.eterfund.ru

server:
  ingress:
    enabled: true
    annotations:
      # kubernetes.io/tls-acme: "true"
      # kubernetes.io/ingress.allow-http: "false"
      # kubernetes.io/ingress.global-static-ip-name: ""
      # cert-manager.io/cluster-issuer: badhouseplants-issuer-http01
    ingressClassName: traefik
    # tls: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  extraArgs:
    - --insecure
  servicePort:
    servicePortHttp: 80
    servicePortHttps: 80
  ingressGrpc:
    # enabled: true
    # annotations:
      # kubernetes.io/tls-acme: "true"
      # kubernetes.io/ingress.allow-http: "false"
      # kubernetes.io/ingress.global-static-ip-name: ""
      # cert-manager.io/cluster-issuer: badhouseplants-issuer-http01
    ingressClassName: traefik
    hostname: "argocdgrpc.k8svkr.eterfund.ru"
    path: /
    pathType: Prefix
    # tls: true

repoServer:
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false

  imagePullSecrets:
    - name: regcred

configs:
  params:
    server.insecure: true
  credentialTemplates:
    ssh-creds:
      url: git@github.com
  ssh:
    # -- Specifies if the argocd-ssh-known-hosts-cm configmap should be created by Helm.
    create: true
    knownHosts: |
       github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
  repositories:
    vaultwarden:
      url: git@github.com:jack-lull/vaultwarden.git
      name: vaultwarden
      type: git
      project: default
    # go-test:
      # url: git@github.com:x/x.git
      # name: go-test
      # type: git
      # project: default
    k8s-cluster-config:
      url: git@github.com:x/x.git
      name: k8s-cluster-config
      type: git
      project: default
    argo-deployment:
      url: git@github.com:x/x.git
      name: argo-deployment
      type: git
      project: default
#applicationSet:
#  metrics:
#    enabled: false
#    serviceMonitor:
#      enabled: false
#
#  repositories:
#    argo-deployment:
#      url: git@github.com:allanger/argo-deployment.git
#      name: argo-deployment
#      insecure: "true"
#      type: git
#    cluster-config:
#      url: git@github.com:allanger/cluster-config.git
#      name: cluster-config
#      insecure: "true"
#      type: git
